### ISSUE TITLE
missing function to get bytearray

### ISSUE THREAD

**Issue by ixje** [NeoResearch/csBigInteger.py#3]
There does not seem to be a function to get a `bytearray` from the BigInteger. This is one of the most used functions in the VM and really a must.

**Comment by ixje** [comment]
To add to this, another important function is to create a BigInteger from a bytearray

**Comment by igormcoelho** [comment]
Thats true, forgot this one. Will do it soon.

**Comment by igormcoelho** [comment]
Done! You can build directly from `bytearray` (or `bytes`) and use `to_bytearray` to convert internal data into a python `bytearray`. 
I will still make it safer, by passing it to library function, instead of getting python one, it will help ensuring correct endianess in all cases. But for now that's correct already.
